### ISSUE TITLE
Server Switching

### ISSUE THREAD

**Issue by oscartbeaumont** [ethanent/onticord#1]
Does this support switching the client between servers without them having to reconnect. Like what bungeecord can do.  Or if it can not is this a feature you are going to add in the future?

**Comment by ethanent** [comment]
Yep, it does indeed! The "basics" plugin that ships with Onticord includes
a server management system which utilizes the API's server-switching method.

I'll have all of this stuff documented in the (very) near future hopefully.
:)

**Comment by oscartbeaumont** [comment]
Awesome because I have been looking for something like this.

**Comment by ethanent** [comment]
Good, same here. I'm really excited about this project!

**Comment by oscartbeaumont** [comment]
Do you run a Minecraft sever that you are building this for?

**Comment by ethanent** [comment]
Sort of, I'm planning on launching one within the coming weeks and it'll be powered by Onticord for dynamic server management. :)
